// TODO: Arrumar as palavras por tópico e adicionar outras palavras

export const words = [
    {
        type: 'easy',
        words: [
            'Avião',
            'Elefante',
            'Bola',
            'Bebê',
            'Peixe',
            'Futebol',
            'Beliscão',
            'Rolo de papel higiênico',
            'Basquete',
            'Controle remoto',
            'Triste',
            'Gato',
            'Golfe',
            'Tesoura',
            'Colher',
            'Pular',
            'Galinha',
            'Sapo',
            'Espirro',
            'Martelo',
            'Violão',
            'Aplaudir',
            'Tosse',
            'Chifres',
            'Pinguim',
            'Chorar',
            'Rabo',
            'Piada',
            'Escova de dente',
            'Celular',
            'Cachorro',
            'Pato',
            'Sofá',
            'Fotógrafo',
            'Óculos de grau',
            'Balé',
            'Pipa',
            'Café',
            'Táxi',
            'Cadeira',
            'Ônibus',
            'Elevador',
            'Bicicleta',
            'Fogão',
            'Copo',
            'Orelhas',
            'Chocolate',
            'Pescador',
            'Notebook',
            'Lápis'
        ]
    },
    {
        type: 'hard',
        words: [
            'Cicatriz',
            'Cobertor',
            'Helicóptero',
            'Aniversário',
            'Vulcão',
            'Arco-íris',
            'Presidente da República',
            'Noiva',
            'Babar',
            'Montanha-russa',
            'Natal',
            'Luz',
            'Sombra',
            'Magia',
            'Maquiadora',
            'Shopping',
            'Berço',
            'Medir',
            'Espelho',
            'Aranha',
            'Moto',
            'Jardim',
            'Trampolim',
            'Cachoeira',
            'Iô-iô',
            'Janela',
            'Girafa',
            'Roncar',
            'Pesadelo',
            'Lanterna',
            'Curiosidade',
            'Panquecas',
            'Aplicativo',
            'Convite',
            'Adolescente',
            'Satélite',
            'Jornal',
            'Diamante',
            'Lenha',
            'Sapo',
            'Andador infantil',
            'Ração',
            'Google',
            'Tocha',
            'Acampar',
            'Lago',
            'Emagrecer',
            'Fofoca',
            'Salário',
            'Sorte'
        ]
    },
    {
        type: 'movies',
        words: [
            'O Poderoso Chefão',
            'O Mágico de Oz',
            'A Culpa é das Estrelas',
            'Minha Mãe é uma Peça',
            'O Amor é Cego',
            'As Branquelas',
            'Clube dos 5',
            'Cantando na Chuva',
            'A Ilha da Fantasia',
            'Branca de Neve e Os Sete Anões',
            'Psicose',
            'Uma Linda Mulher',
            'Central do Brasil',
            'Titanic',
            'Duro de Matar',
            'Cidade de Deus',
            'O Sexto Sentido',
            'E.T. O Extraterrestre',
            'Forest Gump',
            'O Exterminador do Futuro',
            'Homem-Aranha',
            'Matrix',
            'O Silêncio dos Homens',
            'O Auto da Compadecida',
            'Logan',
            'Náufrago',
            'A Paixão de Cristo',
            'Garota Exemplar',
            'King Kong',
            'Gladiador'
        ]
    },
    {
        type: 'animals',
        words: [
            'Borboleta',
            'Cavalo',
            'Cachorro',
            'Caranguejo',
            'Chimpanzé',
            'Coelho',
            'Jacaré',
            'Elefante',
            'Galinha',
            'Girafa',
            'Leão',
            'Gato',
            'Sapo',
            'Veado',
            'Tigre',
            'Grilo',
            'Formiga',
            'Abelha',
            'Hipopótamo',
            'Golfinho',
            'Tigre',
            'Capivara',
            'Esquilo',
            'Rato',
            'Porco',
        ]
    },
    {
        type: 'movie characters',
        words: [
            'Batman',
            'Coringa',
            'Darth Vader',
            'Loki',
            'Vitor Corleone',
            'Capitão América',
            'James Bond',
            'Yoda',
            'Xerife Woody',
            'Capitão Jack Sparrow',
            'Norman Bates',
            'Maximus',
            'Groot',
            'Lord Voldemort',
        ]
    }
];